---
apiVersion: v1
kind: Template
metadata:
  name: swatch-api
parameters:
  - name: ENV_NAME
    value: env-swatch-api
  - name: IMAGE
    value: quay.io/cloudservices/rhsm-subscriptions
  - name: IMAGE_TAG
    value: latest

objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: swatch-api
  pullSecrets:
    name: ${IMAGE_PULL_SECRET}
  spec:
    envName: ${ENV_NAME}
    # Can't have this checked in like this, because stage gets upset since there
# is no rhsm ClowdApp deployed to the rhsm-stage namespace
    # database:
    #   sharedDbAppName: rhsm
    # dependencies:
    #   - rhsm
    deployments:
      - name: service
        minReplicas: 1
        webServices:
          public:
            enabled: true
        podSpec:
          image: ${IMAGE}:${IMAGE_TAG}
          command:
            - /bin/bash
            - /usr/local/s2i/run
          initContainers:
            - env:
                - name: SPRING_PROFILES_ACTIVE
                  value: liquibase-only
              inheritEnv: true
              command:
                - /bin/bash
                - /usr/local/s2i/run
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
          env:
            - name: ENABLE_SPLUNK_HEC
              value: ${ENABLE_SPLUNK_HEC}
            - name: SPLUNKMETA_namespace
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: SPLUNKMETA_host
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: SPLUNK_HEC_URL
              value: ${SPLUNK_HEC_URL}
            - name: SPLUNK_HEC_TOKEN
              valueFrom:
                secretKeyRef:
                  name: splunk-hec-external
                  key: token
            - name: SPLUNK_SOURCE
              value: ${SPLUNK_SOURCE}
            - name: SPLUNK_SOURCE_TYPE
              value: ${SPLUNK_SOURCE_TYPE}
            - name: SPLUNK_MESSAGE_FORMAT
              value: ${SPLUNK_MESSAGE_FORMAT}
            - name: SPLUNK_HEC_CONNECT_TIMEOUT
              value: ${SPLUNK_HEC_CONNECT_TIMEOUT}
            - name: SPLUNK_HEC_BATCH_SIZE
              value: ${SPLUNK_HEC_BATCH_SIZE}
            - name: SPLUNK_HEC_TERMINATION_TIMEOUT
              value: ${SPLUNK_HEC_TERMINATION_TIMEOUT}
            - name: SPRING_PROFILES_ACTIVE
              value: api
            # turn off built-in jolokia, so that the spring boot jolokia actuator will work
            - name: AB_JOLOKIA_OFF
              value: 'true'
            - name: SERVER_MAX_HTTP_HEADER_SIZE
              value: ${SERVER_MAX_HTTP_HEADER_SIZE}
            - name: LOG_FILE
              value: /logs/server.log
            - name: JAVA_MAX_MEM_RATIO
              value: '85'
            - name: GC_MAX_METASPACE_SIZE
              value: '256'
            - name: LOGGING_LEVEL_ROOT
              value: ${LOGGING_LEVEL_ROOT}
            - name: LOGGING_LEVEL_ORG_CANDLEPIN
              value: ${LOGGING_LEVEL}
            - name: KAFKA_MESSAGE_THREADS
              value: ${KAFKA_MESSAGE_THREADS}
            - name: KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS
              value: ${KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS}
            - name: KAFKA_SEEK_OVERRIDE_END
              value: ${KAFKA_SEEK_OVERRIDE_END}
            - name: KAFKA_SEEK_OVERRIDE_TIMESTAMP
              value: ${KAFKA_SEEK_OVERRIDE_TIMESTAMP}
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: rhsm-db
                  key: db.host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: rhsm-db
                  key: db.port
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rhsm-db
                  key: db.user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rhsm-db
                  key: db.password
            - name: DATABASE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: rhsm-db
                  key: db.name
            - name: DATABASE_CONNECTION_TIMEOUT_MS
              value: ${DATABASE_CONNECTION_TIMEOUT_MS}
            - name: DATABASE_MAX_POOL_SIZE
              value: ${DATABASE_MAX_POOL_SIZE}
            - name: INVENTORY_DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: host-inventory-db
                  key: db.host
            - name: INVENTORY_DATABASE_DATABASE
              valueFrom:
                secretKeyRef:
                  name: host-inventory-db
                  key: name
            - name: INVENTORY_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: host-inventory-db
                  key: db.user
            - name: INVENTORY_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: host-inventory-db
                  key: password
            - name: CLOUDIGRADE_ENABLED
              value: ${CLOUDIGRADE_ENABLED}
            - name: PROM_URL
              value: ${PROM_URL}
            - name: OPENSHIFT_BILLING_MODEL_FILTER
              value: ${OPENSHIFT_BILLING_MODEL_FILTER}
            - name: USER_HOST
              value: ${USER_HOST}
            - name: USER_MAX_CONNECTIONS
              value: ${USER_MAX_CONNECTIONS}
            - name: USER_MAX_ATTEMPTS
              value: ${USER_MAX_ATTEMPTS}
            - name: USER_BACK_OFF_MAX_INTERVAL
              value: ${USER_BACK_OFF_MAX_INTERVAL}
            - name: USER_BACK_OFF_INITIAL_INTERVAL
              value: ${USER_BACK_OFF_INITIAL_INTERVAL}
            - name: USER_BACK_OFF_MULTIPLIER
              value: ${USER_BACK_OFF_MULTIPLIER}
            - name: TALLY_SUMMARY_PRODUCER_MAX_ATTEMPTS
              value: ${TALLY_SUMMARY_PRODUCER_MAX_ATTEMPTS}
            - name: TALLY_SUMMARY_PRODUCER_BACK_OFF_MAX_INTERVAL
              value: ${TALLY_SUMMARY_PRODUCER_BACK_OFF_MAX_INTERVAL}
            - name: TALLY_SUMMARY_PRODUCER_BACK_OFF_INITIAL_INTERVAL
              value: ${TALLY_SUMMARY_PRODUCER_BACK_OFF_INITIAL_INTERVAL}
            - name: TALLY_SUMMARY_PRODUCER_BACK_OFF_MULTIPLIER
              value: ${TALLY_SUMMARY_PRODUCER_BACK_OFF_MULTIPLIER}
            - name: RHSM_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tls
                  key: keystore_password
            - name: RHSM_KEYSTORE
              value: /pinhead/keystore.jks
            - name: RHSM_RBAC_USE_STUB
              value: ${RHSM_RBAC_USE_STUB}
            - name: DEV_MODE
              value: ${DEV_MODE}
            - name: SWATCH_SELF_PSK
              valueFrom:
                secretKeyRef:
                  name: swatch-psks
                  key: self
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/liveness
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
          volumeMounts:
            - name: logs
              mountPath: /logs
            - name: pinhead
              mountPath: /pinhead
          volumes:
            - name: logs
              emptyDir:
            - name: pinhead
              secret:
                secretName: pinhead
