---
apiVersion: v1
kind: Template
metadata:
  name: swatch-api
parameters:
  - name: ENV_NAME
    value: env-swatch-api
  - name: IMAGE
    value: registry.access.redhat.com/ubi8/ubi-minimal
  - name: IMAGE_TAG
    value: latest

objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: swatch-api
    pullSecrets:
      name: ${IMAGE_PULL_SECRET}
    spec:
      envName: ${ENV_NAME}
      deployments:
        - name: service
          podSpec:
            image: ${IMAGE}:${IMAGE_TAG}
            command:
              - sleep
            args:
              - 99d