---
apiVersion: v1
kind: Template
metadata:
  name: rhsm
parameters:
  - name: IMAGE_PULL_SECRET
    value: quay-cloudservices-pull
  - name: ENV_NAME
    value: env-rhsm
  - name: IMAGE
    value: quay.io/cloudservices/rhsm-subscriptions
  - name: IMAGE_TAG
    value: latest

objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdApp
  metadata:
    name: rhsm
  spec:
    # The name of the ClowdEnvironment providing the services
    envName: ${ENV_NAME}
    dependencies:
      - host-inventory
    optionalDependencies:
      - cloudigrade

    database:
      # Must specify both a name and a major postgres version
      name: rhsm-db
      version: 12

    pullSecrets:
      name: ${IMAGE_PULL_SECRET}

- apiVersion: v1
  kind: Secret
  metadata:
    name: swatch-psks
  data:
    self: ZHVtbXk=
