---
apiVersion: v1
kind: Template
metadata:
  name: swatch-system-conduit
parameters:
  - name: ENV_NAME
    value: env-swatch-system-conduit
  - name: IMAGE
    value: quay.io/cloudservices/rhsm-subscriptions
  - name: IMAGE_TAG
    value: latest

objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdApp
    metadata:
      name: swatch-system-conduit
    pullSecrets:
      name: ${IMAGE_PULL_SECRET}
    spec:
      envName: ${ENV_NAME}
      deployments:
        - name: service
          podSpec:
            image: ${IMAGE}:${IMAGE_TAG}
            command:
              - sleep
            args:
              - 99d